import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import {
	ClerkProvider,
	SignInButton,
	SignedIn,
	SignedOut,
	UserButton,
} from '@clerk/nextjs';
import { ConvexClientProvider } from '@/components/ConvexProvider';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Halo',
	description: 'Generated by create next app',
	icons: '/sparkles.svg',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ClerkProvider>
			<html lang='en'>
				<body
					className={`${inter.className} bg-gradient-to-br from-pink-100  via-purple-200 to-pink-100`}
				>
					<ConvexClientProvider>{children}</ConvexClientProvider>
				</body>
			</html>
		</ClerkProvider>
	);
}
